### ISSUE TITLE
This extension seems to break the layout of IMDB web pages

### ISSUE THREAD

**Issue by waldens** [txusko/PostItAll-ChromeExtension#1]
The overall page will be to the left and cannot scroll up and down.

Sample page: https://www.imdb.com/title/tt8243158/
Tested on Post It All Version 0.0.1.2 + win7x64 + Cent Browser 3.6.8.99 (Chromium 69.0.3497.100) and all other extensions are disabled, only this extension is enabled

Only I met or it's really a bug?

**Comment by ahmedhamdy90** [comment]
I have the same problem too, is there any solution??

**Comment by txusko** [comment]
Issue fixed in v0.0.1.3, currently in Production.
